trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'bhaveshsivakoti/devops-app'
  tag: 'v1'

steps:

# ✅ FIX: Checkout code
- checkout: self

# ✅ Build Docker
- task: Docker@2
  displayName: Build Image
  inputs:
    command: build
    repository: $(imageName)
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

# ✅ Login DockerHub
- task: Docker@2
  displayName: Login DockerHub
  inputs:
    command: login
    containerRegistry: 'dockerhub-service-connection'

# ✅ Push Image
- task: Docker@2
  displayName: Push Image
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      $(tag)

# ✅ Deploy to K8s
- task: Kubernetes@1
  displayName: Deploy to K8s
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-service-connection'
    namespace: default
    command: apply
    useConfigurationFile: true
    configuration: |
      deployment.yaml
      service.yaml
